project_name: dynamodbtocsv

release:
  github:
    owner: KaushikNeelichetty
    name: dynamodbtocsv

before:
  hooks:
  - go mod download

builds:
- main: ./main.go
  binary: dynamodbtocsv
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - amd64
  - 386
brew:
  name: dynamodbtocsv
  github:
    owner: KaushikNeelichetty
    name: homebrew-tap
  url_template: "https://github.com/KaushikNeelichetty/dynamodbtocsv/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  folder: Formula
  homepage: "https://kaushikneelichetty.github.io/"
  description: "Dump your DynamoDB table as CSV"
