project_name: dynamodbtocsv

release:
  github:
    owner: KaushikNeelichetty
    name: dynamodbtocsv

builds:
- main: ./main.go
  binary: dynamodbtocsv
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - amd64
  - 386